[build]
  publish = "netlify/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self)"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "jsonwebtoken"]

[build.environment]

[dev]
  port = 8888
  publish = "netlify/public"
  functions = "netlify/functions"